apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: ritwik310/scheduler-server
          ports:
            - containerPort: 5000
          env:
            - name: AUTH_REDIRECT_URL_BASE
              valueFrom:
                secretKeyRef:
                  name: auth-redirect-url-base
                  key: AUTH_REDIRECT_URL_BASE

            - name: MONGO_URI
              value: mongodb://mongo-cluster-ip-service:27017/scheduler

            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: google-client-id
                  key: GOOGLE_CLIENT_ID

            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: google-client-secret
                  key: GOOGLE_CLIENT_SECRET

            - name: GOOGLE_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google-refresh-token
                  key: GOOGLE_REFRESH_TOKEN

            - name: GOOGLE_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: google-access-token
                  key: GOOGLE_ACCESS_TOKEN

            - name: MAIL_SENDER_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: mail-sender-address
                  key: MAIL_SENDER_ADDRESS

            - name: EMAIL_TOKEN_KEY
              valueFrom:
                secretKeyRef:
                  name: email-token-key
                  key: EMAIL_TOKEN_KEY

            - name: FACEBOOK_APP_ID
              valueFrom:
                secretKeyRef:
                  name: facebook-app-id
                  key: FACEBOOK_APP_ID
                  
            - name: FACEBOOK_APP_SECRET
              valueFrom:
                secretKeyRef:
                  name: facebook-app-secret
                  key: FACEBOOK_APP_SECRET
                  
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: cookie-key
                  key: COOKIE_KEY